### ISSUE TITLE
Toggle (toggle.js file)

### ISSUE THREAD

**Issue by mattycare** [FatMedia/FatKit#10]
f-toggle doesn't work on iOS when an animation is specified in data-f-toggle.
Sent email to Alex with more details.

**Comment by ahallicks** [comment]
Animations seem to work on the FatKit site. I wonder if someone (me) forgot to add the auto-prefix to the site they weren't working on... there was also an issue with earlier Grunt versions of FatKit where the same thing happened, but Jim and I fixed this.
