### ISSUE TITLE
Mobile menu shown on Desktop

### ISSUE THREAD

**Issue by anth12** [FatMedia/FatKit#9]
When the mobile menu is opened on a narrow screen which is then expanded to a size at which the menu would not normally show (browser window expanded or tablet flipped to landscape)- the offcanvas menu remains active.

![fatkit mobile menu shown on desktop](https://cloud.githubusercontent.com/assets/4281124/9003868/a5337584-3769-11e5-85de-7c2ee6cb444c.png)

To replicate:
- Resize a browser to <960px wide
- Open the offcanvas menu
- Resize the browser to >960px wide

**Comment by jimbateson** [comment]
Just wondering if this would be a site specific tweak you would make.

As I think the off canvas stuff is setup to work across all resolutions. Don't think there is any presets to remove at higher resolutions. Would maybe have to hide if you needed to, if that makes sense?

Unless this is something we should really be doing by default.

**Comment by ahallicks** [comment]
I would say this is site-specific for display of the off-canvas bar, but there is a display issue when orientation is changed so that will need to be fixed.

**Comment by ahallicks** [comment]
Fixed in https://github.com/FatMedia/FatKit/commit/a9d9ba280016e9d95050889cb9846a1d221c035a
